# Generated by Django 3.2.5 on 2021-07-07 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('role', models.IntegerField(choices=[(0, 'Admin'), (1, 'General'), (2, 'Guest'), (3, 'Accounting'), (4, 'IT')], default=1)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_created_user', to=settings.AUTH_USER_MODEL, verbose_name='Created User')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_updated_user', to=settings.AUTH_USER_MODEL, verbose_name='Updated User')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
